# Generated by Django 2.0 on 2018-07-14 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180624_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='event_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='input',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
